In [1]:
import numpy as np 
x= [[1, 2], [2, 3], [3, 4], [4, 5]]
np.array(x).ravel()

array([1, 2, 2, 3, 3, 4, 4, 5])

In [12]:
np.array([1,2,4]).tolist()

[1, 2, 4]

In [24]:
np.random.choice(300, 6)

array([  5, 265,  60, 128,  51,   5])

In [17]:
y = [12, 0, 4, 2]
np.argsort(y), np.sort(y)[::-1]

(array([1, 3, 2, 0]), array([12,  4,  2,  0]))

In [4]:
import torch

In [ ]:
# KnN 
def dis(a, b): 
    return np.sqrt(np.sum(a-b)**2)

def predict(x, X, k): 
    distances = []
    for i in X: 
        distances.append(dis(i, x))
    return np.argmax()
