In [9]:
import torch
# Stage 1: PyTorch Basics

In [5]:
torch.randn((3, 4))

tensor([[-0.2998, -1.7342,  0.7148,  0.0622],
        [ 0.1768,  1.7425, -2.2632,  1.0246],
        [ 0.0991, -0.4391, -0.9792, -0.9587]])

In [6]:
a = torch.tensor([1, 2])
b = torch.tensor([3, 4])

print(a + b)
print(a * b)
print(torch.dot(a.float(), b.float()))


tensor([4, 6])
tensor([3, 8])
tensor(11.)


In [10]:
x = torch.tensor([1, 2, 3])
x = x.unsqueeze(0)     # Shape: [1, 3]
x

tensor([[1, 2, 3]])

In [12]:
x = torch.tensor([1, 2, 3])
x = x.squeeze(0)       # Shape: [3]
x

tensor([1, 2, 3])

In [23]:
# 🧪 Exercise
# Create a 3x3 matrix and compute its transpose

# Normalize a tensor to mean=0, std=1

x= torch.tensor([[1, 2,3 ], [3, 4, 5], [6, 7, 8]], dtype=torch.float32) # Ensure float type for normalization
print("Original matrix:")
print(x)

print("\nTranspose of the matrix:")
print(x.transpose(0, 1))

# Normalize the tensor
mean = torch.mean(x)
std = torch.std(x)
print(mean, std)
normalized_x = (x - mean) / std

print("\nNormalized tensor (mean=0, std=1):")
print(normalized_x)

Original matrix:
tensor([[1., 2., 3.],
        [3., 4., 5.],
        [6., 7., 8.]])

Transpose of the matrix:
tensor([[1., 3., 6.],
        [2., 4., 7.],
        [3., 5., 8.]])
tensor(4.3333) tensor(2.3452)

Normalized tensor (mean=0, std=1):
tensor([[-1.4213, -0.9949, -0.5685],
        [-0.5685, -0.1421,  0.2843],
        [ 0.7107,  1.1371,  1.5635]])


In [8]:

x = torch.tensor([2.0], requires_grad=True)
y = x**2 + 3*x + 1
y.backward()                    # Compute dy/dx
print(x.grad)                   # Gradient: dy/dx at x=2


tensor([7.])


In [25]:
'''This code uses a PyTorch context manager called torch.no_grad(). Here's what it does:

with torch.no_grad():: This line starts a block of code where gradient calculations are disabled.
Why disable gradients? When you're training a neural network, PyTorch automatically tracks the operations performed on tensors to compute gradients during the backward pass (used for optimization). However, during inference (when you're just using the trained model to make predictions) or when you're evaluating the model's performance, you don't need to compute gradients. Disabling gradient calculation in these cases offers several benefits:
Memory saving: It reduces memory consumption because PyTorch doesn't need to store intermediate values required for gradient computation.
Speed improvement: It can speed up computations slightly because the overhead of tracking operations for gradients is removed.
y = model(x):
Inside the with torch.no_grad():
 block, this line performs a forward pass through your model using the input x.
 The result is stored in y. Because this is within the no_grad() context, no gradient information will be tracked for the operations within the model during this forward pass.
In summary, with torch.no_grad(): is used to perform operations with tensors without building the computation graph for gradient calculation.
This is typically done during inference or evaluation phases of a model.
'''
# with torch.no_grad():
#     y = model(x)


"This code uses a PyTorch context manager called torch.no_grad(). Here's what it does:\n\nwith torch.no_grad():: This line starts a block of code where gradient calculations are disabled.\nWhy disable gradients? When you're training a neural network, PyTorch automatically tracks the operations performed on tensors to compute gradients during the backward pass (used for optimization). However, during inference (when you're just using the trained model to make predictions) or when you're evaluating the model's performance, you don't need to compute gradients. Disabling gradient calculation in these cases offers several benefits:\nMemory saving: It reduces memory consumption because PyTorch doesn't need to store intermediate values required for gradient computation.\nSpeed improvement: It can speed up computations slightly because the overhead of tracking operations for gradients is removed.\ny = model(x): \nInside the with torch.no_grad():\n block, this line performs a forward pass throu

Stage 1: PyTorch Basics

In [27]:
#  Stage 3: Building Neural Networks
import torch.nn as nn
class Simple_FCC(nn.Module):
    def __init__(self, input_size, hidden_layers, output_size):
        super().__init__()
        self.linear = nn.Linear(3, 1)
        print(self.linear)

n = Simple_FCC()
n

Linear(in_features=3, out_features=1, bias=True)


Simple_FCC(
  (linear): Linear(in_features=3, out_features=1, bias=True)
)

In [44]:
import torch.nn.functional as F
class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(3, 2)
        self.linear2 = nn.Linear(2, 1)

    def forward(self, x):
        return F.relu(self.linear2(self.linear1(x)))

model = SimpleNN()
print(model(torch.randn(1, 3)))

tensor([[0.]], grad_fn=<ReluBackward0>)


In [45]:
torch.randn(3, 1, 3)

tensor([[[-0.7839,  0.6424,  0.1884]],

        [[ 0.4831, -0.5884, -0.9183]],

        [[ 0.7919,  1.1880, -0.2667]]])

In [47]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Create some dummy data for demonstration
# In a real scenario, you would load your dataset and use a DataLoader
# x_dummy = torch.randn(10, 1, 3) # 10 samples, batch size 1, 3 input features
# y_dummy = torch.randn(10, 1)   # 10 samples, batch size 1, 1 output feature

x_dummy = torch.randn(1000, 1, 3) # 10 samples, batch size 1, 3 input features
y_dummy = torch.randn(1000, 1)   # 10 samples, batch size 1, 1 output feature

for epoch in range(10):
    # Simulate iterating over batches
    # In a real scenario, a DataLoader would handle batching
    for i in range(x_dummy.size(0)):
        x_batch = x_dummy[i].unsqueeze(0) # Get one sample and add a batch dimension
        y_batch = y_dummy[i].unsqueeze(0) # Get one target and add a batch dimension

        # Forward pass
        pred = model(x_batch).squeeze(-1) # Squeeze the output to match the target shape

        # Compute loss
        loss = criterion(pred, y_batch)

        # Backward pass and optimization
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

    print(f'Epoch {epoch+1}, Loss: {loss.item():.4f}')

Epoch 1, Loss: 0.0178
Epoch 2, Loss: 0.0178
Epoch 3, Loss: 0.0178
Epoch 4, Loss: 0.0178
Epoch 5, Loss: 0.0178
Epoch 6, Loss: 0.0178
Epoch 7, Loss: 0.0178
Epoch 8, Loss: 0.0178
Epoch 9, Loss: 0.0178
Epoch 10, Loss: 0.0178


In [52]:
batch_size = 64


In [55]:
import torchvision.datasets as datasets
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
from tqdm import tqdm  # For nice progress bar!
# Load Data
train_dataset = datasets.MNIST(
    root="dataset/", train=True, transform=transforms.ToTensor(), download=True
)
test_dataset = datasets.MNIST(
    root="dataset/", train=False, transform=transforms.ToTensor(), download=True
)
train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=True)

In [56]:
train_loader

In [57]:
# Imports
import torch
import torch.nn.functional as F  # Parameterless functions, like (some) activation functions
import torchvision.datasets as datasets  # Standard datasets
import torchvision.transforms as transforms  # Transformations we can perform on our dataset for augmentation
from torch import optim  # For optimizers like SGD, Adam, etc.
from torch import nn  # All neural network modules
from torch.utils.data import (
    DataLoader,
)  # Gives easier dataset managment by creating mini batches etc.
from tqdm import tqdm  # For nice progress bar!
class NN(nn.Module):
    def __init__(self, input_size, num_classes):
        super(NN, self).__init__()
        self.fc1 = nn.Linear(input_size, 50)
        self.fc2 = nn.Linear(50, num_classes)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Hyperparameters
input_size = 784
num_classes = 10
learning_rate = 0.001
batch_size = 64
num_epochs = 3

# Load Data
train_dataset = datasets.MNIST(
    root="dataset/", train=True, transform=transforms.ToTensor(), download=True
)
test_dataset = datasets.MNIST(
    root="dataset/", train=False, transform=transforms.ToTensor(), download=True
)
train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=True)

# Initialize network
model = NN(input_size=input_size, num_classes=num_classes).to(device)

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Train Network
for epoch in range(num_epochs):
    for batch_idx, (data, targets) in enumerate(tqdm(train_loader)):
        # Get data to cuda if possible
        data = data.to(device=device)
        targets = targets.to(device=device)

        # Get to correct shape
        data = data.reshape(data.shape[0], -1)

        # Forward
        scores = model(data)
        loss = criterion(scores, targets)

        # Backward
        optimizer.zero_grad()
        loss.backward()

        # Gradient descent or adam step
        optimizer.step()


# Check accuracy on training & test to see how good our model
def check_accuracy(loader, model):
    num_correct = 0
    num_samples = 0
    model.eval()

    # We don't need to keep track of gradients here so we wrap it in torch.no_grad()
    with torch.no_grad():
        # Loop through the data
        for x, y in loader:

            # Move data to device
            x = x.to(device=device)
            y = y.to(device=device)
            # linear fully connected layer 1*28*28 = [batch_size, 784]
            # Get to correct shape
            x = x.reshape(x.shape[0], -1)

            # Forward pass
            scores = model(x)
            _, predictions = scores.max(1)

            # Check how many we got correct
            num_correct += (predictions == y).sum()

            # Keep track of number of samples
            num_samples += predictions.size(0)

    model.train()
    return num_correct / num_samples


# Check accuracy on training & test to see how good our model
print(f"Accuracy on training set: {check_accuracy(train_loader, model)*100:.2f}")
print(f"Accuracy on test set: {check_accuracy(test_loader, model)*100:.2f}")

100%|██████████| 938/938 [00:11<00:00, 82.05it/s]


Accuracy on training set: 95.74
Accuracy on test set: 95.22
