In [1]:
# prompt: import pytorch or install it first and import it

try:
  import torch
  print("PyTorch is already installed.")
except:
  print("PyTorch is not installed. Installing now.")
  !pip install torch torchvision torchaudio
  import torch
  print("PyTorch installed successfully.")

PyTorch is already installed.


In [2]:
# prompt: print its version

torch.__version__

'2.6.0+cu124'

In [4]:
import torch
'''The output is a PyTorch tensor. It's a multi-dimensional array of numbers.
 In this case, it's a 3x45 tensor, meaning it has 3 rows and 45 columns,
  filled with random numbers between 0 and 1.'''
torch.rand(3, 45)


tensor([[0.6376, 0.3877, 0.7083, 0.7028, 0.0716, 0.8720, 0.7015, 0.0229, 0.0224,
         0.8555, 0.7353, 0.2372, 0.0651, 0.4687, 0.0928, 0.5462, 0.4914, 0.0469,
         0.2397, 0.0139, 0.7153, 0.3563, 0.0401, 0.2731, 0.3355, 0.7089, 0.2064,
         0.8610, 0.6608, 0.3225, 0.9751, 0.0973, 0.7404, 0.2951, 0.5906, 0.7136,
         0.1496, 0.6254, 0.2256, 0.0377, 0.3803, 0.2080, 0.6969, 0.9990, 0.0840],
        [0.7922, 0.7105, 0.6041, 0.1225, 0.0294, 0.7868, 0.6970, 0.2253, 0.2482,
         0.6291, 0.8046, 0.4581, 0.8785, 0.6433, 0.2417, 0.2480, 0.6424, 0.7183,
         0.0239, 0.6264, 0.8596, 0.2369, 0.5667, 0.0307, 0.8499, 0.8797, 0.9162,
         0.6527, 0.7073, 0.2032, 0.8427, 0.5764, 0.9337, 0.8393, 0.5017, 0.1322,
         0.6811, 0.1289, 0.2361, 0.6718, 0.4499, 0.2722, 0.2304, 0.9150, 0.2863],
        [0.5089, 0.8167, 0.3853, 0.4297, 0.9605, 0.2697, 0.8794, 0.9534, 0.2853,
         0.3594, 0.7016, 0.7526, 0.9493, 0.4222, 0.8126, 0.5090, 0.4095, 0.5747,
         0.6833, 0.4789, 0

In [5]:
my_tensor = torch.tensor([[1, 2, 3], [3, 4, 5]], dtype= torch.float32)
my_tensor

tensor([[1., 2., 3.],
        [3., 4., 5.]])

In [2]:
import torch
print(torch.cuda.is_available())

True


In [3]:
my_tensor = torch.tensor([[1, 2, 3], [3, 4, 5]], dtype= torch.float32, device= "cuda", requires_grad=True)
my_tensor

tensor([[1., 2., 3.],
        [3., 4., 5.]], device='cuda:0', requires_grad=True)

In [4]:
my_tensor.device, my_tensor.shape

(device(type='cuda', index=0), torch.Size([2, 3]))

In [5]:
print("torch.ones((3,3))\n", torch.ones((3, 3)))
print("torch.eye((3,3))\n", torch.eye(3, 3))
print("torch.zeroes((3,3))\n", torch.zeros((3, 3)))
print("torch.rand((3,3))\n", torch.rand((3, 3)))
print("torch.empty((3,3))\n", torch.empty(size= (3, 3)))
print("torch.diag((3,3))\n", torch.diag(torch.ones(3)))

torch.ones((3,3))
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.eye((3,3))
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
torch.zeroes((3,3))
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.rand((3,3))
 tensor([[0.9590, 0.1700, 0.1176],
        [0.9655, 0.4229, 0.7727],
        [0.8834, 0.4766, 0.2751]])
torch.empty((3,3))
 tensor([[1.8032e+23, 4.4693e-41, 1.8032e+23],
        [4.4693e-41, 3.5762e-25, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
torch.diag((3,3))
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [12]:
tensor = torch.arange(3)
print(tensor)
print(tensor.long())
print(tensor.half())
print(tensor.float())


tensor([0, 1, 2])
tensor([0, 1, 2])
tensor([0., 1., 2.], dtype=torch.float16)
tensor([0., 1., 2.])


In [17]:
import numpy as np
arr= np.zeros((1, 3))
tensor = torch.from_numpy(arr)
print(tensor)
back_to_np = tensor.numpy()
print(back_to_np)

tensor([[0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0.]]


In [18]:
x= torch.tensor([1, 2, 3])
y= torch.tensor([4, 5, 6])
z1= torch.empty(3)
torch.add(x, y, out= z1)
print(z1)
z2= torch.add(x, y)
print(z2)

tensor([5., 7., 9.])
tensor([5, 7, 9])


In [21]:
print(x*y)
# dot will element-wise multiply and then add
print(torch.dot(x, y))

tensor([ 4, 10, 18])
tensor(32)


In [25]:
matrx = torch.rand(5, 5)
print(matrx)
print(matrx.matrix_power(3))

tensor([[0.9782, 0.7413, 0.2753, 0.0467, 0.6866],
        [0.2673, 0.9578, 0.6481, 0.9817, 0.3700],
        [0.9456, 0.5415, 0.4750, 0.7065, 0.0543],
        [0.3676, 0.9871, 0.5851, 0.0298, 0.6395],
        [0.3357, 0.6892, 0.6281, 0.8981, 0.7363]])
tensor([[4.5405, 6.5693, 4.3250, 4.4798, 4.1087],
        [5.1560, 7.5189, 5.0102, 5.3708, 4.4209],
        [4.3828, 6.0564, 3.9709, 4.4195, 3.7557],
        [4.3758, 6.4731, 4.2397, 4.1318, 3.8845],
        [5.2996, 7.6966, 5.1387, 5.4869, 4.6044]])


In [30]:
x= torch.arange(10)
x[(x<2) | (x>8)]
torch.where((x>5), x, x*2)

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

In [36]:
x= torch.rand((2, 4))
y = torch.rand((2, 4))
z= torch.cat((x, y), dim = 1)
z.shape

torch.Size([2, 8])

In [38]:
z.view(-1)

tensor([0.7035, 0.8561, 0.6150, 0.3352, 0.3045, 0.6032, 0.1159, 0.7918, 0.4218,
        0.0725, 0.7954, 0.5528, 0.7977, 0.8974, 0.4051, 0.3770])

In [48]:
batch = 64
x = torch.rand((batch, 2, 5))
x.shape

torch.Size([64, 2, 5])

In [47]:
x.view(batch , -1).shape

torch.Size([64, 10])

In [50]:
x.permute(0, 2 , 1).shape

torch.Size([64, 5, 2])

In [56]:
x= torch.arange(10)
print(x.shape)
x.unsqueeze(0).shape

torch.Size([10])


torch.Size([1, 10])

In [55]:
x.unsqueeze(1).shape

torch.Size([10, 1])

In [57]:
x.unsqueeze(0).unsqueeze(1).shape

torch.Size([1, 1, 10])